Developed by: AmirMasoud Nourollah  <br>
Instructor by: Prof. Hamid Hassanpour <br>
Reviewed by: Abdollah Zakeri


In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
display(a)

array([1, 2, 3, 4])

------------------
- 1D  &#8594; Vector: \[ 1, 2, 3 , 4\] (1D Tensor)
- 2D  &#8594; Matrix: $\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ (2D Tensor)
- 3D  &#8594; Cube: \[\[\[1, 2\], \[3 , 4\]\]\] (3D Tensor)
- 4D  &#8594; Tesseract
- 5D  &#8594; ?
...
- nD  &#8594; Tensor

in general we call them **Tensor**

In [3]:
print(f"#Dims: {a.ndim}")
print(f"#Shape: {a.shape}")
print(f"#Type: {a.dtype}")
print(f"#Size: {a.size}")
print(f"#ItemSize: {a.itemsize}")
print(f"#Memory Usage: {a.itemsize * a.size}")
print(f"#Memory Usage: {a.nbytes}")

#Dims: 1
#Shape: (4,)
#Type: int64
#Size: 4
#ItemSize: 8
#Memory Usage: 32
#Memory Usage: 32


In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype='uint8')
display(a)

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

In [5]:
print("#Dims: ", a.ndim)
print("#Shape: ", a.shape)
print("#Type: ", a.dtype)
print("#Size: ", a.size)
print("#ItemSize: ", a.itemsize)
print("#Memory Usage: ", a.itemsize * a.size)
print("#Memory Usage: ", a.nbytes)

#Dims:  2
#Shape:  (2, 3)
#Type:  uint8
#Size:  6
#ItemSize:  1
#Memory Usage:  6
#Memory Usage:  6


In [6]:
a = np.array([[[1],[2],[3]], [[4], [5], [6]]])
display(a)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [7]:
a.ndim

3

In [8]:
a.shape

(2, 3, 1)

In [13]:
# Creates a vector between start & stop with step
temp = np.arange(5, 15, 0.5).reshape(4,5)

In [14]:
temp.shape

(4, 5)

In [15]:
temp

array([[ 5. ,  5.5,  6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5, 12. ],
       [12.5, 13. , 13.5, 14. , 14.5]])

In [10]:
# Create n numbers between two numbers with fixed length
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.zeros((3,2,1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [28]:
a = np.arange(30)

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
a.shape

(30,)

In [30]:
a.reshape((6,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [31]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
a.reshape((5,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [32]:
a.reshape((5, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [33]:
a = a.reshape((5, -1))

In [34]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [36]:
temp = np.arange(5).reshape(-1,1)

In [37]:
temp.shape

(5, 1)

In [38]:
np.arange(5).reshape(1,-1)

array([[0, 1, 2, 3, 4]])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
np.arange(10).reshape(2,5).T.reshape(-1)

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [43]:
np.arange(10).reshape((2,5), order='F')

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [44]:
np.arange(10).reshape((5,2)).T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [45]:
a = np.arange(100).reshape(-1, 2)

In [49]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [47]:
type(a)

numpy.ndarray

In [48]:
a[10]

array([20, 21])

In [50]:
a[10][0]

20

In [51]:
a[10, 0]

20

In [55]:
a[2:7]

array([[ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [56]:
a[:15]

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [58]:
t = a[-4:]

In [59]:
t

array([[92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [ ]:
a[2:11:2] # [start:stop:step]

array([[ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [60]:
a[:, 0] 

array([ 4,  8, 12, 16, 20])

In [63]:
w = 10
h = 10
# GrayScale
a = np.random.randint(0, 255, size=(w,h,3))
display(a[:,:,0])
display(a[:,:,1])
display(a[:,:,2])

array([[154, 215, 169, 151,  78, 169,  36,  10, 203, 240],
       [ 39,  41,   8, 154, 191, 176, 112, 231,  27, 142],
       [215, 204,  66,  22, 114,  84,  48, 187, 241, 252],
       [ 45, 113, 225,  53, 209,  42,   7, 226, 207, 239],
       [245, 236, 222, 231,  44,   2,  25, 209, 219, 168],
       [ 13, 233, 132,  66, 105,  39, 154, 166, 119,  31],
       [  5,  49,  25, 110, 228, 100, 193, 217, 172,  20],
       [100, 211,  69, 128,  89,  86, 134, 112,  43, 113],
       [169,  32,  40,  49,  33, 103,  87,  88,  76,  41],
       [ 23,   7, 146,  79, 140,  79, 126, 113,  20,  69]])

array([[122,   3, 126, 215, 237, 111,  58, 243, 240,  63],
       [  0, 163,  13,  45, 209,  59, 239, 201, 177,  18],
       [241, 119,  62,  32,  74, 194,  18, 139,  27, 165],
       [153,  86,  90, 218, 238,   8,  18, 250, 163, 170],
       [212,  56, 150, 156, 205, 225,  99, 150,  82, 170],
       [ 45,  22,  13,  92, 252, 147,  39, 230, 104, 239],
       [ 46, 202, 187, 182, 145,  72, 246,  53,  88, 222],
       [ 47,  24, 210,  45, 242, 230, 195,  48, 105, 247],
       [160, 208, 253, 246,  12, 226, 127, 176, 202, 191],
       [193, 154, 208,  40, 141,  61, 149,  63, 211, 140]])

array([[ 41, 199, 163,  77,  28, 190,  56, 190, 180,  18],
       [191,  16, 181,  55, 120, 127, 238, 154,  82, 179],
       [249, 172, 246,  51,  99, 101, 121,  51,  26, 149],
       [216,  47,  49,  13, 218, 254, 236, 241,  73,  37],
       [123, 159,  97, 232,  87, 186, 197,  21,  20,  71],
       [194, 140, 164, 116,  69,  41,  99, 207, 210,  42],
       [134,  25, 205, 170,  79,  82,  63, 175,  64, 113],
       [254,  95, 186, 201, 228,  25,  73, 184, 254, 239],
       [226, 144, 129,  37, 139,  61, 163,  20,  29, 249],
       [ 46,  34,  69, 104, 234,   0, 187,  14,  52, 233]])

In [64]:
b = np.arange(30).reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [65]:
b[::2, 1::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [66]:
b[[0,3], :] 

array([[ 0,  1,  2,  3,  4,  5],
       [18, 19, 20, 21, 22, 23]])

In [67]:
b[[0,2], [3,1]] # -> (0,3) & (2,1) 

array([ 3, 13])

In [68]:
b 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [71]:
b ** 2  # Elementwise operation 

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529],
       [576, 625, 676, 729, 784, 841]])

In [72]:
b + 2

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31]])

In [73]:
2 + b

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31]])

In [74]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [75]:
c = np.ones(6)
c

array([1., 1., 1., 1., 1., 1.])

In [76]:
b + c

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.]])

In [77]:
d = np.array([1,2,3,4,5,6])
b + d  # Numpy Broadcast

array([[ 1,  3,  5,  7,  9, 11],
       [ 7,  9, 11, 13, 15, 17],
       [13, 15, 17, 19, 21, 23],
       [19, 21, 23, 25, 27, 29],
       [25, 27, 29, 31, 33, 35]])

In [78]:
d = np.array([1,2,3,4,5,6])
b + d  # Numpy Broadcast

array([[ 1,  3,  5,  7,  9, 11],
       [ 7,  9, 11, 13, 15, 17],
       [13, 15, 17, 19, 21, 23],
       [19, 21, 23, 25, 27, 29],
       [25, 27, 29, 31, 33, 35]])

In [79]:
np.broadcast_to(d, (5,6))

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [80]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [81]:
b[[0, 0, -1, -1] , [0,-1, -1, 0]]

array([ 0,  5, 29, 24])

In [82]:
e = np.arange(9).reshape(3,3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
np.diag(e)

array([0, 4, 8])

In [84]:
e.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [85]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [86]:
b % 2

array([[0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1]])

In [87]:
f = b % 2 == 0
f

array([[ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [88]:
b[f]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [89]:
b[b%2==0] 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [90]:
g = b>5
g

array([[False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [91]:
f & g 

array([[False, False, False, False, False, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [92]:
f | g

array([[ True, False,  True, False,  True, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [93]:
b[(b>3) & (b<8)] 

array([4, 5, 6, 7])

In [94]:
b[~((b>3) & (b<8))]

array([ 0,  1,  2,  3,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29])